version: '3'
services:
  api:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: "postgres://svc:password@db:5432/invest_analytics"
      PGRST_DB_SCHEMAS: "invest_analytics"
      PGRST_DB_ANON_ROLE: "svc"
      PGRST_OPENAPI_SERVER_PROXY_URI: "http://127.0.0.1:3000"
    healthcheck:
     test: ["CMD-SHELL", "pg_isready -U postgres"]
     interval: 5s
     timeout: 10s
     retries: 15
    container_name: invest-analytics-api
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/
    container_name: invest-analytics-swagger
